friends=('srikanth','Loki','Chandu','Sunil')
print('-'*70)
print("Created tuple is :",friends)
print('-'*70)
print("Third person in tuple is : ",friends[2])
print("From 3-4 friends are : ",friends[2:5])
print('-'*70)
print("All members in friends tuple are : ")
for i in friends:
    print(i)
print('-'*70)
print("Length of Friends tuple is : ",len(friends))
print('-'*70)
friends2 = ('Mahesh','Sandeep','Usman','Venkat')
print("Tuple concatenation : ",friends+friends2)
print('-'*70)
#Finding index of the element
print("Loki index number is : ",friends.index('Loki'))
print('-'*70)
